# Generated by Django 4.2.13 on 2024-07-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0004_alter_materialadaptado_is_disponivel_para_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_impressa', models.PositiveBigIntegerField(default=0)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado')),
            ],
        ),
    ]
