# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_registro',
            field=models.DateField(verbose_name='Data da impressão'),
        ),
    ]
