# Generated by Django 4.2.13 on 2024-07-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_materialadaptado_is_disponivel_para_pedido'),
        ('estoque', '0002_alter_estoque_data_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_impressa', models.PositiveBigIntegerField(default=0)),
                ('data_registro', models.DateField(verbose_name='Data da impressão')),
                ('material', models.OneToOneField(limit_choices_to={'tipo': 'braille'}, on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado')),
            ],
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
