# Generated by Django 5.0.1 on 2024-01-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('material', '0002_alter_material_quantidade_paginas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
    ]
