# Generated by Django 5.0.1 on 2024-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_assinatura_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='assinatura',
        ),
        migrations.AddField(
            model_name='cliente',
            name='assinaturas',
            field=models.ManyToManyField(to='cliente.assinatura'),
        ),
    ]
