# Generated by Django 5.0.1 on 2024-01-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_assinatura_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='assinaturas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
    ]
