# Generated by Django 5.0.1 on 2024-02-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_assinatura_data_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da pessoa que receberá o material')),
                ('assinatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.assinatura')),
            ],
        ),
    ]
