# Generated by Django 4.2.11 on 2024-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_assinatura_data_ultima_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro'),
        ),
    ]
