# Generated by Django 4.2.11 on 2024-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_alter_assinatura_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
    ]
