# Generated by Django 5.0.1 on 2024-04-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_alter_assinatura_estado_alter_assinatura_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvioRevistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_envio', models.DateTimeField(null=True)),
                ('revistas', models.ManyToManyField(to='cliente.assinatura')),
            ],
        ),
    ]
