# Generated by Django 4.2.11 on 2024-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_registroenviorevistas_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroenviorevistas',
            old_name='revistas',
            new_name='assinaturas',
        ),
    ]
