# Generated by Django 5.0.1 on 2024-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_alter_registroenvioassinaturas_assinaturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroenvioassinaturas',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroenvioassinaturas',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro'),
        ),
    ]
