# Generated by Django 4.2.11 on 2024-04-29 20:06

import cliente.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_alter_material_arquivo_original_and_more'),
        ('cliente', '0023_rename_cliente_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoMaterialAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to=cliente.models.get_material_upload_path)),
                ('assinaturas', models.ManyToManyField(blank=True, limit_choices_to={'estado': 'vigente'}, null=True, to='cliente.assinatura')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado')),
                ('registro_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.registroenvioassinaturas')),
            ],
        ),
    ]
