# Generated by Django 4.2.11 on 2024-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0027_remove_registroenvioassinaturas_assinaturas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenvioassinaturas',
            name='estado',
            field=models.CharField(choices=[('enviado', 'enviado'), ('não enviado', 'enviado')], default='enviado', max_length=255),
            preserve_default=False,
        ),
    ]
