# Generated by Django 4.2.11 on 2024-05-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_materialadaptado_tamanho'),
        ('cliente', '0034_alter_edicaomaterialassinatura_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroenvioassinaturas',
            name='estado',
        ),
        migrations.AddField(
            model_name='registroenvioassinaturas',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edicaomaterialassinatura',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_disponivel_para_assinatura': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado'),
        ),
        migrations.AlterField(
            model_name='edicaomaterialassinatura',
            name='quantidade_paginas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
