# Generated by Django 4.2.11 on 2024-05-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0035_remove_registroenvioassinaturas_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroenvioassinaturas',
            name='data_envio',
        ),
        migrations.AlterField(
            model_name='registroenvioassinaturas',
            name='enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado?'),
        ),
    ]
