# Generated by Django 4.2.11 on 2024-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0037_edicaomaterialassinatura_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicaomaterialassinatura',
            name='quantidade_assinaturas_Es',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='edicaomaterialassinatura',
            name='quantidade_assinaturas_OE',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='edicaomaterialassinatura',
            name='quantidade_assinaturas_RJ',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
