# Generated by Django 5.0.1 on 2024-01-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('nome_contato', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'nenhuma'), ('1', 'cancelado'), ('2', 'vigente')], max_length=2)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('assinaturas', models.ManyToManyField(to='assinatura.assinatura')),
                ('contato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.contato')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255)),
                ('assinatura', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255)),
                ('assinatura', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.assinatura')),
            ],
        ),
    ]
