# Generated by Django 5.0.1 on 2024-01-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0001_initial'),
        ('pedido', '0002_remove_pedido_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='assinatura',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='pedidos',
            field=models.ManyToManyField(to='pedido.pedido'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('contato', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.contato')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.pessoa'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='pessoa',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.pessoa'),
        ),
    ]
