# Generated by Django 4.2.13 on 2024-06-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='Revista',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_disponivel_para_assinatura': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.revista'),
        ),
        migrations.AddField(
            model_name='edicaomaterialassinatura',
            name='revista',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_disponivel_para_assinatura': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.revista'),
        ),
    ]
