# Generated by Django 4.2.13 on 2024-06-07 18:39

import assinatura.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0002_assinatura_revista_edicaomaterialassinatura_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoRevistaAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_paginas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('peso', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to=assinatura.models.get_revista_upload_path)),
                ('quantidade_assinaturas_RJ', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qtd. ass. Rio de Janeiro (ativas)')),
                ('quantidade_assinaturas_Es', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qtd. ass. Estrangeiros (ativas)')),
                ('quantidade_assinaturas_OE', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Qtd. ass. Outros Estados (ativas)')),
            ],
            options={
                'verbose_name': 'Edição da Assinatura',
                'verbose_name_plural': 'Edições da Assinatura',
            },
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='Revista',
            new_name='revista',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='material',
        ),
        migrations.DeleteModel(
            name='EdicaoMaterialAssinatura',
        ),
        migrations.AddField(
            model_name='edicaorevistaassinatura',
            name='assinaturas',
            field=models.ManyToManyField(limit_choices_to={'estado': 'vigente'}, to='assinatura.assinatura'),
        ),
        migrations.AddField(
            model_name='edicaorevistaassinatura',
            name='registro_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.registroenvioassinaturas'),
        ),
        migrations.AddField(
            model_name='edicaorevistaassinatura',
            name='revista',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_disponivel_para_assinatura': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.revista'),
        ),
    ]
