# Generated by Django 4.2.13 on 2024-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0003_edicaorevistaassinatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicaorevistaassinatura',
            options={'verbose_name': 'Edição da Revista', 'verbose_name_plural': 'Edições das Revistas (que serão enviadas)'},
        ),
        migrations.AlterModelOptions(
            name='remessa',
            options={'verbose_name': 'Remessa', 'verbose_name_plural': 'Remessas para Envio (das edições das revistas)'},
        ),
    ]
