# Generated by Django 5.0.1 on 2024-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0004_assinatura_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='observacao',
            field=models.CharField(default=1, max_length=255, verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='estado',
            field=models.CharField(choices=[('1', 'vigente'), ('0', 'cancelado')], default='vigente', max_length=2),
        ),
    ]
