# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0004_alter_edicaorevistaassinatura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome da pessoa que receberá a revista'),
        ),
    ]
