# Generated by Django 5.0.1 on 2024-01-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0005_assinatura_observacao_alter_assinatura_estado'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='material',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='material_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinatura',
            name='material_object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
