# Generated by Django 4.2.11 on 2024-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0012_alter_assinatura_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data_ultima_alteracao',
            field=models.DateTimeField(null=True),
        ),
    ]
