# Generated by Django 4.2.11 on 2024-04-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0019_rename_revistas_registroenviorevistas_assinaturas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroEnvioRevistas',
            new_name='RegistroEnvioAssinaturas',
        ),
        migrations.AlterModelOptions(
            name='registroenvioassinaturas',
            options={'verbose_name_plural': 'Registro de envio de Assinaturas'},
        ),
    ]
