# Generated by Django 4.2.11 on 2024-04-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0013_pessoajuridica_tipo_instituicao_and_more'),
        ('pedido', '0018_alter_pedido_observacao_alter_pedido_registro_envio'),
        ('assinatura', '0022_alter_registroenvioassinaturas_data_envio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Solicitante',
        ),
    ]
