# Generated by Django 4.2.11 on 2024-05-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0025_alter_edicaomaterialassinatura_assinaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenvioassinaturas',
            name='nome',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinatura.solicitante', verbose_name='Solicitante / Assinante'),
        ),
    ]
