# Generated by Django 4.2.11 on 2024-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0028_registroenvioassinaturas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroenvioassinaturas',
            name='estado',
            field=models.CharField(choices=[('enviado', 'enviado'), ('não enviado', 'não enviado')], max_length=255),
        ),
    ]
