# Generated by Django 4.2.11 on 2024-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0029_alter_registroenvioassinaturas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='registroenvioassinaturas',
            name='identificacao',
            field=models.CharField(blank=True, default='Cecograma', max_length=255, verbose_name='Identificação'),
        ),
        migrations.AddField(
            model_name='registroenvioassinaturas',
            name='remetente',
            field=models.CharField(blank=True, default='Instituto Benjamin Constant', max_length=255, verbose_name='Remetente'),
        ),
    ]
