# Generated by Django 4.2.11 on 2024-05-06 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0030_remessa_registroenvioassinaturas_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remessa',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remessa',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remessa',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='remessa',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remessa',
            name='registro_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assinatura.registroenvioassinaturas'),
        ),
        migrations.AddField(
            model_name='remessa',
            name='tipo_remessa',
            field=models.CharField(choices=[('estrangeiros', 'estrangeiros'), ('RJ', 'RJ'), ('Outros Estados', 'Outros Estados')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
