# Generated by Django 4.2.11 on 2024-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0031_remessa_data_envio_remessa_data_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='remessa',
            name='tipo_remessa',
        ),
        migrations.AddField(
            model_name='remessa',
            name='tipo_remessa',
            field=models.ManyToManyField(max_length=255, to='assinatura.tiporemessa'),
        ),
    ]
