# Generated by Django 4.2.11 on 2024-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0033_remessa_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicaomaterialassinatura',
            options={'verbose_name': 'Edição da Assinatura', 'verbose_name_plural': 'Edições da Assinatura'},
        ),
        migrations.AlterModelOptions(
            name='registroenvioassinaturas',
            options={'verbose_name_plural': 'Configurar envio de Assinaturas'},
        ),
        migrations.AlterModelOptions(
            name='remessa',
            options={'verbose_name': 'Remessa', 'verbose_name_plural': 'Remessas para Envio (de edições de assinaturas)'},
        ),
        migrations.AlterField(
            model_name='registroenvioassinaturas',
            name='estado',
            field=models.CharField(choices=[('enviado', 'enviado'), ('não enviado', 'não enviado')], default='não enviado', max_length=255),
        ),
    ]
