# Generated by Django 4.2.11 on 2024-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0036_remove_registroenvioassinaturas_data_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicaomaterialassinatura',
            name='peso',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
