# Generated by Django 4.2.13 on 2024-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0039_alter_edicaomaterialassinatura_quantidade_assinaturas_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
