# Generated by Django 4.2.13 on 2024-06-06 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0040_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
    ]
