# Generated by Django 4.2.13 on 2024-06-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pessoa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('is_estrangeiro', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Estrageiro?')),
                ('nacionalidade', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('cpf', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('tipo_instituicao', models.CharField(blank=True, choices=[('Associações', 'Associações'), ('Bibliotecas', 'Bibliotecas'), ('Centros', 'Centros'), ('Escolas', 'Escolas'), ('Fundações', 'Fundações'), ('Governo', 'Governo'), ('Instituições', 'Instituições'), ('Universidades', 'Universidades')], max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pessoa', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('pessoa', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoafisica')),
                ('bio', models.TextField(blank=True)),
                ('matricula', models.CharField(max_length=255)),
                ('profissao', models.CharField(max_length=255)),
                ('foto', models.FileField(blank=True, null=True, upload_to=pessoa.models.get_foto_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
            },
            bases=('pessoa.pessoafisica',),
        ),
    ]
