# Generated by Django 5.0.1 on 2024-01-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa'),
            preserve_default=False,
        ),
    ]
