# Generated by Django 5.0.1 on 2024-01-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_remove_pessoafisica_id_remove_pessoafisica_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.endereco'),
        ),
    ]
