# Generated by Django 5.0.1 on 2024-01-23 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_contato_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
    ]
