# Generated by Django 5.0.1 on 2024-01-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_remove_pessoa_contato_remove_pessoa_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='pessoa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pessoa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
    ]
