# Generated by Django 5.0.1 on 2024-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_alter_contato_pessoa_alter_endereco_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
