# Generated by Django 5.0.1 on 2024-01-26 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_pessoafisica_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
