# Generated by Django 5.0.1 on 2024-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_endereco_pais_pessoa_is_estrangeiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_estrangeiro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Estrageiro?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro', max_length=255, null=True),
        ),
    ]
