# Generated by Django 5.0.1 on 2024-02-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_alter_pessoa_data_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_registro',
            field=models.DateField(null=True),
        ),
    ]
