# Generated by Django 4.2.11 on 2024-03-21 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_endereco_bairro_alter_pessoa_data_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'verbose_name_plural': 'Pessoas Jurídicas'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_registro',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_estrangeiro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Estrageiro?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
