# Generated by Django 5.0.1 on 2024-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_alter_pessoa_options_alter_pessoafisica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_estrangeiro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Estrageiro?'),
        ),
    ]
