# Generated by Django 5.0.1 on 2024-04-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0012_alter_pessoa_data_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='tipo_instituicao',
            field=models.CharField(blank=True, choices=[('Associações', 'Associações'), ('Bibliotecas', 'Bibliotecas'), ('Centros', 'Centros'), ('Escolas', 'Escolas'), ('Fundações', 'Fundações'), ('Governo', 'Governo'), ('Instituições', 'Instituições'), ('Universidades', 'Universidades')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
