# Generated by Django 4.2.11 on 2024-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0013_pessoajuridica_tipo_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
