# Generated by Django 5.0.1 on 2024-05-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_alter_endereco_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoafisica')),
                ('matricula', models.CharField(max_length=255)),
                ('profissao', models.CharField(max_length=255)),
            ],
            bases=('pessoa.pessoafisica',),
        ),
    ]
