# Generated by Django 5.0.1 on 2024-05-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0016_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
    ]
