# Generated by Django 4.2.13 on 2024-06-05 15:35

from django.db import migrations, models
import pessoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0018_funcionario_bio_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=pessoa.models.get_foto_upload_path),
        ),
    ]
