# Generated by Django 5.0.1 on 2024-01-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('didático', 'didático'), ('paradidático', 'paradidático'), ('revista', 'revista'), ('DAL (S/Revisão)', 'DAL (S/Revisão)'), ('Outro', 'Outro')], max_length=255)),
                ('acervo', models.CharField(max_length=255)),
                ('tiragem', models.CharField(max_length=255)),
                ('quantidade_paginas', models.IntegerField()),
                ('arquivo_original', models.FileField(upload_to='arquivos/%Y/%m')),
                ('is_disponivel_para_assinatura', models.BooleanField(default=False)),
                ('is_disponivel_para_pedido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAmpliado',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.material')),
                ('quantidade_paginas_ampliada', models.IntegerField()),
                ('arquivo_braille', models.FileField(upload_to='arquivos/ampliado/%Y/%m')),
                ('partes', models.IntegerField()),
            ],
            bases=('material.material', models.Model),
        ),
        migrations.CreateModel(
            name='MaterialBraille',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.material')),
                ('arquivo_braille', models.FileField(upload_to='arquivos/braille/%Y/%m')),
                ('quantidade_paginas_braille', models.IntegerField()),
                ('partes', models.IntegerField()),
            ],
            bases=('material.material', models.Model),
        ),
    ]
