# Generated by Django 5.0.1 on 2024-01-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('didático', 'didático'), ('paradidático', 'paradidático'), ('revista', 'revista'), ('DAL (S/Revisão)', 'DAL (S/Revisão)'), ('Outro', 'Outro')], max_length=255)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('acervo', models.CharField(max_length=255)),
                ('tiragem', models.CharField(max_length=255)),
                ('quantidade_paginas', models.PositiveIntegerField()),
                ('arquivo_original', models.FileField(upload_to='arquivos/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAmpliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_paginas_ampliada', models.PositiveIntegerField()),
                ('partes', models.PositiveIntegerField()),
                ('is_disponivel_para_assinatura', models.BooleanField(default=False, verbose_name='disponibilizar para assinatura?')),
                ('is_disponivel_para_pedido', models.BooleanField(default=False, verbose_name='disponibilizar para pedido?')),
                ('arquivo_ampliado', models.FileField(upload_to='arquivos/ampliado/%Y/%m')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBraille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_paginas_braille', models.PositiveIntegerField()),
                ('partes', models.PositiveIntegerField()),
                ('is_disponivel_para_assinatura', models.BooleanField(default=False)),
                ('is_disponivel_para_pedido', models.BooleanField(default=False)),
                ('arquivo_braille', models.FileField(upload_to='arquivos/braille/%Y/%m')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
        ),
    ]
