# Generated by Django 4.2.13 on 2024-06-06 19:25

from django.db import migrations, models
import django.db.models.deletion
import material.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('didático', 'didático'), ('paradidático', 'paradidático'), ('revista', 'revista'), ('DAL (S/Revisão)', 'DAL (S/Revisão)'), ('Outro', 'Outro')], max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('edicao', models.CharField(blank=True, max_length=255, null=True)),
                ('editora', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Público alvo')),
                ('acervo', models.CharField(blank=True, max_length=255, null=True)),
                ('tiragem', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to=material.models.get_material_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='MaterialAdaptado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('braille', 'braille'), ('ampliado', 'ampliado')], max_length=255)),
                ('quantidade_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('tamanho', models.PositiveIntegerField(blank=True, null=True)),
                ('partes', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=material.models.get_material_upload_path)),
                ('is_disponivel_para_pedido', models.BooleanField(default=False, verbose_name='Disponível para pedido?')),
                ('is_disponivel_para_assinatura', models.BooleanField(default=False, verbose_name='Disponível para assinatura?')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'verbose_name_plural': 'Materiais Adaptados',
            },
        ),
    ]
