# Generated by Django 5.0.1 on 2024-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantidade_paginas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialampliado',
            name='partes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialampliado',
            name='quantidade_paginas_ampliada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialbraille',
            name='partes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='materialbraille',
            name='quantidade_paginas_braille',
            field=models.PositiveIntegerField(),
        ),
    ]
