# Generated by Django 5.0.1 on 2024-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbraille',
            name='is_disponivel_para_assinatura',
            field=models.BooleanField(default=False, verbose_name='Disponível para assinatura?'),
        ),
        migrations.AlterField(
            model_name='materialbraille',
            name='is_disponivel_para_pedido',
            field=models.BooleanField(default=False, verbose_name='Disponível para pedido?'),
        ),
    ]
