# Generated by Django 4.2.13 on 2024-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialadaptado',
            name='is_disponivel_para_assinatura',
        ),
    ]
