# Generated by Django 4.2.13 on 2024-06-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_materialadaptado_is_disponivel_para_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialadaptado',
            name='is_disponivel_para_pedido',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disponível para pedido?'),
        ),
        migrations.AlterField(
            model_name='materialadaptado',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_adaptados', to='material.material'),
        ),
    ]
