# Generated by Django 5.0.1 on 2024-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_materialbraille_is_disponivel_para_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo_original',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='materialampliado',
            name='arquivo_ampliado',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/ampliado/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='materialbraille',
            name='arquivo_braille',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/braille/%Y/%m'),
        ),
    ]
