# Generated by Django 5.0.1 on 2024-02-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_arquivo_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbraille',
            name='material',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='tipo',
            new_name='classificacao',
        ),
        migrations.CreateModel(
            name='MaterialAdaptado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('braille', 'braille'), ('ampliado', 'ampliado')], max_length=255)),
                ('quantidade_paginas', models.PositiveIntegerField()),
                ('partes', models.PositiveIntegerField()),
                ('is_disponivel_para_assinatura', models.BooleanField(default=False, verbose_name='Disponível para assinatura?')),
                ('is_disponivel_para_pedido', models.BooleanField(default=False, verbose_name='Disponível para pedido?')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/braille/%Y/%m')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialAmpliado',
        ),
        migrations.DeleteModel(
            name='MaterialBraille',
        ),
    ]
