# Generated by Django 4.2.13 on 2024-07-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_material_ano_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='classificacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='material.classificacao'),
            preserve_default=False,
        ),
    ]
