# Generated by Django 4.2.11 on 2024-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='acervo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='edicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='editora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tiragem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
