# Generated by Django 4.2.11 on 2024-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_material_acervo_alter_material_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantidade_paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
