# Generated by Django 4.2.11 on 2024-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_material_publico_alvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialadaptado',
            name='partes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialadaptado',
            name='quantidade_paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
