# Generated by Django 4.2.11 on 2024-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_alter_material_arquivo_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo_original',
            field=models.FileField(blank=True, null=True, upload_to='materiais/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='materialadaptado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='"materiais/adaptados/"+{tipo}+"/%Y/%m"'),
        ),
    ]
