# Generated by Django 4.2.11 on 2024-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_alter_material_arquivo_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialadaptado',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='"materiais/adaptados/"+<django.db.models.fields.CharField>+"/%Y/%m"'),
        ),
    ]
