# Generated by Django 4.2.11 on 2024-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_alter_material_arquivo_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialadaptado',
            name='tamanho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
