# Generated by Django 4.2.13 on 2024-06-06 19:25

from django.db import migrations, models
import django.db.models.deletion
import pedidoAdaptacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('material', '0001_initial'),
        ('assinatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAdaptacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('quantidade_solicitada', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=500, verbose_name='descrição')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinatura.solicitante')),
            ],
            options={
                'verbose_name_plural': 'Pedidos de adaptação',
            },
        ),
        migrations.CreateModel(
            name='Transcricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_transcricao', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da transcrição')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('arquivo_transcrito', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Transcrições',
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de finalização')),
                ('arquivo_revisado', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('estado_revisao', models.CharField(choices=[('novo', 'novo'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], default='novo', max_length=255)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
                ('transcricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.transcricao')),
            ],
            options={
                'verbose_name_plural': 'Revisões',
            },
        ),
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_impressao', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da impressão')),
                ('tipo_impressao', models.CharField(choices=[('BRAILLE', 'BRAILLE'), ('AMPLIADO', 'AMPLIADO')], max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('quantidade_paginas_impressas', models.PositiveIntegerField(verbose_name='quantidade de páginas impressas')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Impressões',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(choices=[('adaptação', 'adaptação'), ('diagramação', 'diagramação'), ('esteriotipia', 'esteriotipia'), ('encadernação', 'encadernação'), ('expedição', 'expedição'), ('revisão', 'revisão'), ('impressão tinta', 'impressão tinta'), ('impressão braille', 'impressão braille'), ('transcrição', 'transcrição')], max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='Esteriotipia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_esteriotipia', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da esteriotipia')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Esteriotipias',
            },
        ),
        migrations.CreateModel(
            name='Encadernacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_encadernacao', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da encadernação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Encadernações',
            },
        ),
        migrations.CreateModel(
            name='Diagramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_diagramacao', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da diagramação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('arquivo_diagramado', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Diagramações',
            },
        ),
        migrations.CreateModel(
            name='Adaptacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_adaptacao', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('pendente', 'pendente'), ('finalizado', 'finalizado')], default='novo', max_length=255, verbose_name='estado da adaptação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de finalização')),
                ('arquivo_adaptado', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Adaptações',
            },
        ),
    ]
