# Generated by Django 4.2.11 on 2024-05-22 20:08

from django.db import migrations, models
import django.db.models.deletion
import pedidoAdaptacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0015_materialadaptado_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAdaptacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'verbose_name_plural': 'Pedidos de adaptação',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(choices=[('adaptação', 'adaptação'), ('diagramação', 'diagramação'), ('esteriotipia', 'esteriotipia'), ('encadernação', 'encadernação'), ('expedição', 'expedição'), ('impressão tinta', 'impressão tinta'), ('impressão braille', 'impressão braille'), ('transcrição', 'transcrição')], max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_inicio', models.DateTimeField(blank=True, verbose_name='Data de registro')),
                ('data_fim', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('profissional', models.CharField(max_length=255)),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path)),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Registo de envio de Pedidos',
            },
        ),
    ]
