# Generated by Django 4.2.11 on 2024-05-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0039_alter_edicaomaterialassinatura_quantidade_assinaturas_es_and_more'),
        ('pedidoAdaptacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'verbose_name_plural': 'Etapas'},
        ),
        migrations.AddField(
            model_name='pedidoadaptacao',
            name='solicitante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_fim',
            field=models.DateTimeField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de início'),
        ),
    ]
