# Generated by Django 4.2.11 on 2024-05-27 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0002_alter_etapa_options_pedidoadaptacao_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoadaptacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nome_etapa',
            field=models.CharField(choices=[('adaptação', 'adaptação'), ('diagramação', 'diagramação'), ('esteriotipia', 'esteriotipia'), ('encadernação', 'encadernação'), ('expedição', 'expedição'), ('revisão', 'revisão'), ('impressão tinta', 'impressão tinta'), ('impressão braille', 'impressão braille'), ('transcrição', 'transcrição')], max_length=255),
        ),
    ]
