# Generated by Django 4.2.11 on 2024-05-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0003_pedidoadaptacao_data_registro_alter_etapa_nome_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Transcrições',
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Revisões',
            },
        ),
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Impressões',
            },
        ),
        migrations.CreateModel(
            name='Esteriotipia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Esteriotipias',
            },
        ),
        migrations.CreateModel(
            name='Encadernacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Encadernações',
            },
        ),
        migrations.CreateModel(
            name='Diagramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Diagramações',
            },
        ),
        migrations.CreateModel(
            name='Adaptacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_adaptacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoAdaptacao.pedidoadaptacao')),
            ],
            options={
                'verbose_name_plural': 'Adaptações',
            },
        ),
    ]
