# Generated by Django 4.2.11 on 2024-05-27 19:51

import datetime
from django.db import migrations, models
import django.utils.timezone
import pedidoAdaptacao.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0004_transcricao_revisao_impressao_esteriotipia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisao',
            name='pedido_adaptacao',
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='arquivo_adaptado',
            field=models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path),
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 48, 27, 569825, tzinfo=datetime.timezone.utc), verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 48, 38, 465663, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 27, 19, 48, 45, 649854, tzinfo=datetime.timezone.utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='profissional',
            field=models.CharField(default=datetime.datetime(2024, 5, 27, 19, 49, 4, 305865, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='arquivo_diagramado',
            field=models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path),
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 49, 23, 649759, tzinfo=datetime.timezone.utc), verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 49, 30, 145915, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='profissional',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 49, 57, 681305, tzinfo=datetime.timezone.utc), verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 50, 11, 441729, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 27, 19, 50, 21, 345664, tzinfo=datetime.timezone.utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='profissional',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 50, 41, 697498, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 27, 19, 50, 53, 729815, tzinfo=datetime.timezone.utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='profissional',
            field=models.CharField(default=datetime.datetime(2024, 5, 27, 19, 51, 4, 1616, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressao',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 51, 5, 985908, tzinfo=datetime.timezone.utc), verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressao',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 51, 8, 338285, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 27, 19, 51, 10, 401477, tzinfo=datetime.timezone.utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressao',
            name='profissional',
            field=models.CharField(default=datetime.datetime(2024, 5, 27, 19, 51, 12, 353581, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisao',
            name='arquivo_revisado',
            field=models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path),
        ),
        migrations.AddField(
            model_name='revisao',
            name='profissional',
            field=models.CharField(default=datetime.datetime(2024, 5, 27, 19, 51, 14, 433465, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcricao',
            name='arquivo_transcrito',
            field=models.FileField(blank=True, null=True, upload_to=pedidoAdaptacao.models.get_material_upload_path),
        ),
        migrations.AddField(
            model_name='transcricao',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 51, 16, 417556, tzinfo=datetime.timezone.utc), verbose_name='Data de finalização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcricao',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 51, 23, 729585, tzinfo=datetime.timezone.utc), verbose_name='Data de início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcricao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 27, 19, 51, 25, 393834, tzinfo=datetime.timezone.utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcricao',
            name='profissional',
            field=models.CharField(default=datetime.datetime(2024, 5, 27, 19, 51, 26, 993284, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
