# Generated by Django 5.0.1 on 2024-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0005_remove_revisao_pedido_adaptacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='quantidade_paginas_impressas',
            field=models.PositiveIntegerField(default=0, verbose_name='qunatidade de páginas impressas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressao',
            name='tipo_impressao',
            field=models.CharField(choices=[('BRAILLE', 'BRAILLE'), ('AMPLIADO', 'AMPLIADO')], default='braille', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoadaptacao',
            name='descricao',
            field=models.CharField(default='', max_length=500, verbose_name='descrição'),
            preserve_default=False,
        ),
    ]
