# Generated by Django 5.0.1 on 2024-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0006_impressao_quantidade_paginas_impressas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptacao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='adaptacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='diagramacao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='diagramacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='encadernacao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='encadernacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='esteriotipia',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='esteriotipia',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='transcricao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='transcricao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
    ]
