# Generated by Django 5.0.1 on 2024-05-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0007_alter_adaptacao_data_fim_alter_adaptacao_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoadaptacao',
            name='quantidade_solicitada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
