# Generated by Django 4.2.11 on 2024-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0009_alter_adaptacao_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptacao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='impressao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='revisao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
        migrations.AddField(
            model_name='transcricao',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
    ]
