# Generated by Django 4.2.11 on 2024-05-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0010_adaptacao_estado_envio_diagramacao_estado_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisao',
            old_name='estado_envio',
            new_name='estado_revisao',
        ),
        migrations.RemoveField(
            model_name='adaptacao',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='diagramacao',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='encadernacao',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='esteriotipia',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='transcricao',
            name='estado_envio',
        ),
        migrations.AddField(
            model_name='adaptacao',
            name='estado_adaptacao',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da adaptação'),
        ),
        migrations.AddField(
            model_name='diagramacao',
            name='estado_diagramacao',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da diagramação'),
        ),
        migrations.AddField(
            model_name='encadernacao',
            name='estado_encadernacao',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da encadernação'),
        ),
        migrations.AddField(
            model_name='esteriotipia',
            name='estado_esteriotipia',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da esteriotipia'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='estado_impressao',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da impressão'),
        ),
        migrations.AddField(
            model_name='transcricao',
            name='estado_transcricao',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255, verbose_name='estado da transcrição'),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='quantidade_paginas_impressas',
            field=models.PositiveIntegerField(verbose_name='quantidade de páginas impressas'),
        ),
    ]
