# Generated by Django 4.2.11 on 2024-05-29 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0012_revisao_transcricao_alter_adaptacao_estado_adaptacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de finalização'),
        ),
        migrations.AddField(
            model_name='revisao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AddField(
            model_name='revisao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revisao',
            name='estado_revisao',
            field=models.CharField(choices=[('aprovado', 'aprovado'), ('recusado', 'recusado')], default='novo', max_length=255),
        ),
    ]
