# Generated by Django 4.2.11 on 2024-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoAdaptacao', '0013_revisao_data_fim_revisao_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisao',
            name='estado_revisao',
            field=models.CharField(choices=[('novo', 'novo'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], default='novo', max_length=255),
        ),
    ]
