# Generated by Django 4.2.13 on 2024-06-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('assinatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvioPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_envio', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('enviado', 'enviado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
            ],
            options={
                'verbose_name_plural': 'Registo de envio de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('numero_pedido', models.PositiveBigIntegerField()),
                ('estado_do_pedido', models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('enviado', 'enviado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('registro_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.registroenviopedidos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinatura.solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('aceito', 'aceito'), ('indisponivel', 'indisponivel'), ('pendente', 'pendente')], max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedido.pedido')),
            ],
        ),
    ]
