# Generated by Django 5.0.1 on 2024-01-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinatura', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('aceito', 'aceito'), ('indisponivel', 'indisponivel'), ('pendente', 'pendente')], max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assinatura.assinatura')),
                ('items', models.ManyToManyField(to='pedido.item')),
            ],
        ),
    ]
