# Generated by Django 5.0.1 on 2024-01-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pedido', '0002_remove_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='material_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='material_object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
