# Generated by Django 5.0.1 on 2024-01-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_assinatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='items',
            new_name='itens',
        ),
    ]
