# Generated by Django 5.0.1 on 2024-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_remove_pedido_itens_pedido_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='pedido.item'),
        ),
    ]
