# Generated by Django 5.0.1 on 2024-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_rename_cliente_pedido_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_do_pedido',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('enviado', 'enviado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
    ]
