# Generated by Django 4.2.11 on 2024-03-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_options_and_more'),
        ('pedido', '0011_alter_pedido_estado_do_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='material',
            field=models.ForeignKey(limit_choices_to={'is_disponivel_para_pedido': True}, on_delete=django.db.models.deletion.CASCADE, to='material.materialadaptado'),
        ),
    ]
