# Generated by Django 4.2.11 on 2024-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_alter_itempedido_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
