# Generated by Django 5.0.1 on 2024-04-18 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0017_remove_registroenviopedidos_pedidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='registro_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.registroenviopedidos'),
        ),
    ]
