# Generated by Django 4.2.11 on 2024-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_alter_pedido_observacao_alter_pedido_registro_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenviopedidos',
            name='estado_envio',
            field=models.CharField(choices=[('novo', 'novo'), ('processado', 'processado'), ('enviado', 'enviado'), ('finalizado', 'finalizado'), ('pendente', 'pendente')], default='novo', max_length=255),
        ),
    ]
